version: '2'
services:
  postgres:
    image: postgres:9.6
    ports:
      - "5432"
    volumes:
      - "./data/postgres/etc:/etc/postgresql"
      - "./data/postgres/log:/var/log/postgresql"
      - "./data/postgres/postgresdb:/var/lib/postgresql/data"
    environment:
      POSTGRES_PASSWORD: lovesaveworld
      POSTGRES_USER: blog_user
      POSTGRES_DB: blog
      DEBUG: "false"
  redis:
    image: redis
    ports:
      - "6379"

  backend:
    build: ./
    ports:
      - "3000"
    command: 'npm run start'
    depends_on:
      - postgres
